[package]
name = "biblebooks"
version = "0.1.0"
authors = ["Adrian Enns <enns@guardtec.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
